name: CI for combiner tool

on:
  pull_request:
    branches: 
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      # need to add this checkout in order to use the file in branch 
      - uses: actions/checkout@v3
      - name: Check syntax errors
        run: python -m py_compile ./combiner/main.py
