# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI for combiner tool

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Tu
          LAST_NAME: Ngo
        run: |
          echo $MY_VAR $FIRST_NAME $LAST_NAME.
